### PR TITLE
Post auth

### LINKED ISSUE #80: API: POST `/auth`
Copied from the [Sprint 2 Plan](https://github.com/Inventor4life/Beef/blob/main/docs/Sprint2Plan.md)

> POST `/auth`

 - Validate the CSRF token
 - Validate Google's token
 - Return `401` if either of those steps failed
 - Send GET `/users?oidcSub={google's sub ID}`
 - If `400` is received, return an error `500` # 400 means corrupted subject ID
 - If `404` is received, Send POST `/users` with the required data structure to create a user; using the name provided by google's token as the `friendlyName` field.
 - Sign a Beef JWT using the returned `User` information.
 - Set that JWT as a header cookie with `Secure; Same-Site: Strict; HttpOnly` options.
 - Redirect the user to `/chat`

### PR DESCRIPTION
**Pull request by Inventor4life**
Closes #80 . GET `/users/me` works now.

### CODE REVIEW

File: services/first-service/src/main.ts [hunk 1]
```diff
@@ -74,6 +63,13 @@ switch(process.env.APP_ENV) {
 		process.exit(1)
 };
 
+const serviceAgent = new Agent({ // Https agent so that this service can call its own endpoints.
```
Comment (Inventor4life) [inline services/first-service/src/main.ts:62]: I didn't add enough documentation to this. Because we are using self-signed certificates, any `fetch()` operations to our endpoints will fail unless we explicitly allow the self-signed certificate.

File: services/first-service/src/auth.ts [hunk 2]
```diff
@@ -1 +1,206 @@
...
+  // 2 was chosen for the following edge case:
+  // reattempt --; (reattempt is 1)
+  // GET user
+  //  -> 401 invalid token
+  // (regenerate token)
+  // reattempt --; (reattempt is 0)
+  // GET user
+  //  -> Some other status
+
+  while(reattempt) {
```
Comment (Inventor4life) [inline services/first-service/src/auth.ts:160]: This code feels rough to me. The main part that feels rough is the retry logic combined with the API wrapper. One of the main scenarios that would require a retry is if the service token is expired. I feel like it would flow better if we had getServiceToken() and regenerateServiceToken() rather than a global variable. Also if we could define a single code "area" to handle `401` errors due to expired tokens rather than relying on the loop to catch it.

I'm open to ideas on how this could be better structured.

File: services/first-service/src/auth.ts [hunk 3]
```diff
@@ -1 +1,206 @@
...
+}
+const getLocalUrl = (path: string) => localUrlPrefix + path;
+
+let serviceAgent: Agent | null = null;
+export function authUseAgent(newAgent: Agent) {
+  serviceAgent = newAgent;
+}
+
+async function userGetFromOidc(serviceToken: string, oidcSub: string) : Promise<User | ApiError>{
+  const res = await fetch(getLocalUrl(`/users?oidcSub=${oidcSub}`),
```
Comment (Cole-Godfrey) [inline services/first-service/src/auth.ts]: Should wrap this in try catch. Even though we check that status is 200, any exceptions are unhandled.

File: services/first-service/src/auth.ts [hunk 4]
```diff
@@ -1 +1,206 @@
...
+      status: res.status,
+      response: res
+    }
+  } // else
+  const aUser = await res.json()
+  return aUser as User // This should always be a User structure if the users endpoint is functioning correctly
+}
+
+async function userCreate(serviceToken: string, newUser: {friendlyName: string, oidcSub: string}) : Promise<User | ApiError> {
+  const res = await fetch(getLocalUrl('/users'), {
```
Comment (Cole-Godfrey) [inline services/first-service/src/auth.ts]: Same as comment above

File: services/first-service/src/auth.ts (hunk 2 above)
Comment (Cole-Godfrey) [reply services/first-service/src/auth.ts:160]: We could immediately regenerate on 401 and retry instead of redoing the entire loop. But it works for now.

**Review by Cole-Godfrey — APPROVED** [review]
